GabayBuhay/views/guest.py
import os
from flask import (Blueprint, current_app, render_template, request, redirect, url_for, session, jsonify, flash, make_response)
from werkzeug.utils import secure_filename
import db

guest_bp = Blueprint('guest_bp', __name__)

@guest_bp.route('/')
def index(): 
    return render_template('guest/index.html')


@guest_bp.route('/registration', methods=['POST'])
def registration():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']  # Retrieve the bcrypt instance from the app config
            user_data = request.form.to_dict(flat=False)  # Convert to a regular dictionary
            password = user_data['password'][0]  # Get the raw password from the form
            repeat_password = user_data['repeat_password'][0]
            
            # Hash the password using Flask-Bcrypt 
            hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
            hashed_repeat_password = bcrypt.generate_password_hash(repeat_password).decode('utf-8')
            # Replace the raw password with the hashed password in the user_data dictionary
            user_data['password'][0] = hashed_password
            user_data['repeat_password'][0] = hashed_repeat_password
            
            db.register_user(user_data)
            #Turn the user_data into a regular dictionary!! 
            user_data = {key: value[0] for key, value in user_data.items()}
            
            # Store user data in the session
            session['user_data'] = user_data
            
            #Redirects the user to his/her respective page based on their role (patient/clinician)
            return redirect(url_for('patient_bp.patient_home'))
            

@guest_bp.route('/log_in', methods=['POST'])
def log_in():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']
            email = request.form['email']
            password = request.form['password']

            user_data = db.fetch_user(email)

            if user_data is None:
                # Invalid credentials
                error_message = 'You have not yet created an account. Please try again.'
                return jsonify({'error': error_message})

            elif not bcrypt.check_password_hash(user_data['password'], password):
                # Invalid credentials
                error_message = 'Invalid credentials. Please try entering the password again.'
                return jsonify({'error': error_message})

            # Successful login
            session['user_data'] = user_data
            
            return jsonify({'success': 'Patient login successful', 'redirect_url': url_for('patient_bp.patient_home')})
      

@guest_bp.route('/about_us')
def about_us():
    return render_template('guest/about_us.html')

GabayBuhay/templates/guest/about_us.html
{% set guest = True %}
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/guest/about_us.css') }}">

{% endblock head %}

{% block title %}About Us{% endblock title %}

{% block content %}

    {# REGISTRATION FORM #}
    {# When user clicks get started, this will pop up#}
    {% include "guest/registration-form.html" %}
    {# LOGIN FORM #}
    {# When user clicks get started, this will pop up#}
    {% include "guest/login-form.html" %}
    <div id="overlay" class="overlay"></div>

    <div class="container-body">
        <div class="slides slide1">
                <div class="row flex-lg-row-reverse align-items-center g-5 px-5 first">
                    <div class="col-10 col-sm-8 col-lg-6">
                        <img src="{{url_for('static', filename='imgs_&_svgs/ABOUT_IMAGE.svg')}}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" loading="lazy" style="margin-top: 20px;" width="600" height="500px">
                    </div>

                    <div class="col-lg-6 py-2 px-5">
                        <h1 class="display-6 fw-bold lh-3 mb-3 text-center" style="font-family: 'Questrial', sans-serif; color:black"> <b> About Us</b></h1> <br>
                        <h1 class="display-5 lh-3 mb-3 text-center" style="font-family: 'Questrial', sans-serif; color:black"> <b> Unlocking dermatological wisdom through information, guiding everyone with clinical decisions.</b></h1>

                            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                            <button id="getStartedBtn" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Get Started</button>
                            </div>
                    </div>

                </div>
        </div>
    </div>

    <div class="container-body">
        <div class="slides slide2"> 
                <div class="row flex-lg-row px-5 first">
                    <h1>What We Are</h1>
                    <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</h4>


                    <div class="image-container">
                        <img src="{{url_for('static', filename='imgs_&_svgs/team3.jpg')}}" class="img-fluid" alt="Bootstrap Themes" loading="lazy">
                    </div>

                </div>
        </div>
    </div>

    <div class="container-body">
        <div class="slides slide3"> 
                <div class="row flex-lg-row px-5 first">
                    <h1>Meet Our Team</h1>
                    <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</h4>


                    <div class="image-container">
                        <img src="{{url_for('static', filename='imgs_&_svgs/team3.jpg')}}" class="img-fluid" alt="Bootstrap Themes" loading="lazy">
                    </div>

                </div>
        </div>
    </div>

 

{% endblock content %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>  
    <script src="{{ url_for('static', filename='js/guest/index_script.js') }}"></script>
{% endblock scripts %}
 

GabayBuhay/templates/guest/index.html
{% set guest = True %}
{% extends "base.html" %}
{% block head %}
    {# super() - the index.html inherits the contents of basehtml head block #}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/guest/style.css') }}">

{% endblock head %}

{% block title %}LichenCare{% endblock title %}

{% block content %}
        {# REGISTRATION FORM #}
        {# When user clicks get started, this will pop up#}
        {% include "guest/registration-form.html" %}
        {# LOGIN FORM #}
        {# When user clicks get started, this will pop up#}
        {% include "guest/login-form.html" %}
        <div id="overlay" class="overlay"></div>
                
<div class="container-body">
          <div class="slides slide2">
              <div class="row flex-lg align-items-center g-5 py-4 px-5 second">
                <div class="col-10 col-sm-8 col-lg-6">
                    <img src="{{url_for('static', filename='imgs_&_svgs/derma2.svg')}}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700px" height="500px" loading="lazy">
                </div>

                <div class="col-lg-6 py-5">
                    <h1 class="display-6 fw-bold lh-3 mb-3 text-wrap" style="font-family: 'Questrial', sans-serif; color:black "> <b> Catalyzing Quality Clinical Outcomes Through Innovative Healthcare Technology.</b></h1>


                    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                    <button id="getStartedBtn" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Get Started</button>
                    </div>
                </div>        
            </div>
          </div>
</div>

  {# Section 1 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section1">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Enhance patient care and improvement outcomes with modern technology</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>GabayBuhay offers a modern healthcare tool for dermatology to provide decisions support for patients and dermatologists with improved healthcare services</b></p>
            </div>
        </div>
        

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button" id="getStartedBtn1">Get to Know More!</a>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/Clinical_Solutions.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>
 
    {# Section 2 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section2">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Dermatology powered by Artificial Intelligence</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>Machine Learning's trend is rising, and GabayBuhay saw this technology as the cornerstone in achieving improved healthcare quality outcomes. Have yourself a skin disease detector that can give an additional layer of screening.</b></p>
            </div>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button" id="getStartedBtn2">Get Started</a>
        </div>
        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/LichenCheck.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>

    {# Section 3 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section3">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Streamlined and increase patient throughput</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>GabayBuhay offers a technology that provides a modern yet more efficient way of responsibly screening patients ahead of their appointment with a dermatologist. This saves time and improves patient throughput making it easy for the clinician to better recognize their patient.</b></p>
            </div>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button" id="getStartedBtn3">Get Started</a>
        </div>
        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/See_A_Doctor.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>


    {# Section 4 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section4">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Learn Dermatology in just a few clicks</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>GabayBuhay extends its function as a Decision Support System by providing educational resources on multiple skin disorders ranging its rarity. This allows patients to make an informed decision about the skin condition diagnosis and learn dermatology with ease.</b></p>
            </div>
        </div>


        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button" id="getStartedBtn4">Get Started</a>
        </div>
        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/DermAware.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>

{% endblock content%}


{% block scripts %}
    {{ super() }}
{% endblock scripts %}

GabayBuhay/templates/guest/login-form.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/guest/login-form_style.css') }}">

<div id="loginFormPopup" class="login-form-popup">
    <div class="container main align-items-center g-5 first">
    
    <div id="error-message-container">
        <div id="error-message" class="error-message"  style="display: none;"></div>
    </div>

    <div id="success-message-container">
        <div id="success-message" class="success-message"  style="display: none;"></div>
    </div>


          <form action="{{ url_for('guest_bp.log_in') }}" id="loginForm" method="POST" enctype="multipart/form-data">
              <div class="input-box">
                
                <div class="row header-row">
                    <div class="col-2 text-start">
                          
                    </div>
                    <div class="col-8 text-center">
                        <h2>Log-in</h2>
                    </div>
                    <div class="col-2 text-end">
                        
                    </div>
                </div>

                <div class="input-field">
                  <label for="email">Email</label>
                  <input type="email" class="input" name = "email" required/> 
                </div>

                <div class="input-field">
                  <label for="email">Password</label> 
                  <input type="password" class="input" name = "password" required/>
                </div>

                <div class="input-field" style="text-align: center;">
                  <input type="submit" class="submit" value="Login">
                </div>

                <!--Sign up here -->
                <div class="signin">
                  <span>Don't have an acount? <a id="redirect_to_register">Sign up here</a></span>
                </div>

              </div>  
        </form>        
    </div>
</div>


{% block script %}

{# JS FOR THE LOGIN-FORM ERROR HANDLING AND SUCCESSFUL LOG IN#}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const loginForm = document.getElementById("loginForm");
        const errorMessage = document.getElementById("error-message");
        const successMessage = document.getElementById("success-message");

        loginForm.addEventListener("submit", function (event) {
            event.preventDefault(); // Prevent the default form submission behavior

            const formData = new FormData(loginForm);

            fetch("{{ url_for('guest_bp.log_in') }}", {
                method: "POST",
                body: formData,
            })
                .then(response => response.json())
                .then(data => {
                    if (data.error) {
                        errorMessage.textContent = data.error;
                        errorMessage.style.display = 'block'; // Show the error message
                    } else if (data.success) {
                        errorMessage.style.display = 'none';
                        successMessage.textContent = data.success; 
                        successMessage.style.display = 'block'; // Show the success message
                        setTimeout(function() {
                            window.location.href = data.redirect_url; // Redirect after a delay
                        }, 1000); // 1000 miliseconds (1s delay)
                    }
                })
                .catch(error => {
                    console.error("Error:", error);
                });
        });
    });
</script>

{% endblock script %}

GabayBuhay/templates/guest/registration-form.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/guest/registration-form_style.css') }}">

<!-- Registration form -->
<div id="registrationFormPopup" class="registration-form-popup">

    <!-- Your registration form HTML code goes here -->
    <div class="container main align-items-center g-5 first">
        <form action="{{ url_for('guest_bp.registration') }}" method="POST" enctype="multipart/form-data">
            <div class="input-box">
                <div class="row header-row">
                    <div class="col-2 text-start">
                        
                    </div>
                    <div class="col-8 text-center">
                        <h2>Create an Account</h2>
                    </div>
                    <div class="col-2 text-end">
                        <button type="button" class="btn-close" aria-label="Close"></button>
                    </div>
                </div>

                <div class="row">
                    <!-- First Name -->
                    <div class="col-6 input-field">
                        <label for="fname">First Name</label>
                        <input type="text" class="input" name="first_name" required/>
                    </div>

                    <!-- Last Name -->
                    <div class="col-6 input-field">
                        <label for="lname">Last Name</label>
                        <input type="text" class="input" name="last_name" required/>
                    </div>
                </div>

                <!-- Email -->
                <div class="input-field">
                    <label for="email">Email</label>
                    <input type="email" class="input" id="email" name="email" required="" autocomplete="off">
                </div>

                <!-- Password -->
                <div class="input-field">
                    <label for="pass">Password</label>
                    <input type="password" class="input" id="pass" name="password" required/>
                </div>

                <!-- Confirm Password -->
                <div class="input-field">
                    <label for="pass">Confirm Password</label>
                    <input type="password" class="input" name="repeat_password" required/>
                </div>
  
                <div class="input-field terms">
                    <label>
                        <input type="checkbox" name="agree_to_terms" required>
                        I agree to the Terms of Service and Privacy Policy
                    </label>
                </div>

                <!-- Sign up button -->
                <div class="input-field" style="text-align: center;">
                    <input type="submit" class="submit" value="Sign Up" href="{{ url_for('guest_bp.registration') }}">
                </div>

                <!-- Login here -->
                <div class="signin">
                    <span>Already have an account? <a id="redirect_to_login">Log in here</a></span>
                </div>
            </div>
        </form>
    </div>
</div>