GabayBuhay/views/guest.py
import os
from flask import (Blueprint, current_app, render_template, request, redirect, url_for, session, jsonify, flash, make_response)
from werkzeug.utils import secure_filename
import db

guest_bp = Blueprint('guest_bp', __name__)

@guest_bp.route('/')
def index(): 
    return render_template('guest/index.html')


@guest_bp.route('/registration', methods=['POST'])
def registration():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']  # Retrieve the bcrypt instance from the app config
            user_data = request.form.to_dict(flat=False)  # Convert to a regular dictionary
            password = user_data['password'][0]  # Get the raw password from the form
            repeat_password = user_data['repeat_password'][0]
            
            # Hash the password using Flask-Bcrypt 
            hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
            hashed_repeat_password = bcrypt.generate_password_hash(repeat_password).decode('utf-8')
            # Replace the raw password with the hashed password in the user_data dictionary
            user_data['password'][0] = hashed_password
            user_data['repeat_password'][0] = hashed_repeat_password
            
            db.register_user(user_data)
            #Turn the user_data into a regular dictionary!! 
            user_data = {key: value[0] for key, value in user_data.items()}
            
            # Store user data in the session
            session['user_data'] = user_data
            
            #Redirects the user to his/her respective page based on their role (patient/clinician)
            return redirect(url_for('patient_bp.patient_home'))
            

@guest_bp.route('/log_in', methods=['POST'])
def log_in():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']
            email = request.form['email']
            password = request.form['password']

            user_data = db.fetch_user(email)

            if user_data is None:
                # Invalid credentials
                error_message = 'You have not yet created an account. Please try again.'
                return jsonify({'error': error_message})

            elif not bcrypt.check_password_hash(user_data['password'], password):
                # Invalid credentials
                error_message = 'Invalid credentials. Please try entering the password again.'
                return jsonify({'error': error_message})

            # Successful login
            session['user_data'] = user_data
            
            return jsonify({'success': 'Patient login successful', 'redirect_url': url_for('patient_bp.patient_home')})
      

@guest_bp.route('/about_us')
def about_us():
    return render_template('guest/about_us.html')

GabayBuhay/views/index.py
import os
from flask import (Blueprint, current_app, render_template, request, redirect, url_for, session, jsonify, flash, make_response)
from werkzeug.utils import secure_filename
import db

home_bp = Blueprint('home_bp', __name__)

@home_bp.route('/')
def index(): 
    roles = db.load_roles_from_db()
    return render_template('index/index.html', roles=roles)


@home_bp.route('/registration', methods=['POST'])
def registration():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']  # Retrieve the bcrypt instance from the app config
            user_data = request.form.to_dict(flat=False)  # Convert to a regular dictionary
            password = user_data['password'][0]  # Get the raw password from the form
            repeat_password = user_data['repeat_password'][0]
            
            # Hash the password using Flask-Bcrypt 
            hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
            hashed_repeat_password = bcrypt.generate_password_hash(repeat_password).decode('utf-8')
            # Replace the raw password with the hashed password in the user_data dictionary
            user_data['password'][0] = hashed_password
            user_data['repeat_password'][0] = hashed_repeat_password
            
            # Handle file upload
            if 'clinician_license' in request.files:
                file = request.files['clinician_license']
                if file.filename != '':
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
                    user_data['clinician_license'] = filename  # Save the filename to the database
                    
            db.register_user(user_data)
            #Turn the user_data into a regular dictionary!! 
            user_data = {key: value[0] for key, value in user_data.items()}
            
            # Store user data in the session
            session['user_data'] = user_data
            
            #Redirects the user to his/her respective page based on their role (patient/clinician)
            if user_data['account_type'] == '1':
                return redirect(url_for('patient_bp.patient_home'))
            elif user_data['account_type'] == '2':
                return redirect(url_for('clinician_bp.clinician_home'))
            

@home_bp.route('/log_in', methods=['POST'])
def log_in():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']
            email = request.form['email']
            password = request.form['password']

            user_data = db.fetch_user(email)

            if user_data is None:
                # Invalid credentials
                error_message = 'You have not yet created an account. Please try again.'
                return jsonify({'error': error_message})

            elif not bcrypt.check_password_hash(user_data['password'], password):
                # Invalid credentials
                error_message = 'Invalid credentials. Please try entering the password again.'
                return jsonify({'error': error_message})

            # Successful login
            session['user_data'] = user_data

            if user_data['role_id'] == 1:
                return jsonify({'success': 'Patient login successful', 'redirect_url': url_for('patient_bp.patient_home')})
            elif user_data['role_id'] == 2:
                return jsonify({'success': 'Clinician login successful', 'redirect_url': url_for('clinician_bp.clinician_home')})
      
      
@home_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    # Remove session variables related to the user's login
    session.pop('user_data', None)  # Remove user ID or any other relevant session variables
    # Redirect the user to the login page or any other appropriate page
    return redirect(url_for('home_bp.index')) 

GabayBuhay/views/patient.py
from flask import (Blueprint, render_template, jsonify, request, redirect, session, make_response, url_for)

import db
patient_bp = Blueprint('patient_bp', __name__)

@patient_bp.route('/patient_home')
def patient_home():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/patient_home.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response


@patient_bp.route('/patient/lichencheck')
def lichencheck():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/lichencheck.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response


@patient_bp.route('/patient/lichenhub')
def lichenhub():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/lichenhub.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response


@patient_bp.route('/patient/licheknow')
def licheknow():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/licheknow.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response

@patient_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    # Remove session variables related to the user's login
    session.pop('user_data', None)  # Remove user ID or any other relevant session variables
    # Redirect the user to the login page or any other appropriate page
    return redirect(url_for('guest_bp.index')) 

GabayBuhay/templates/patient/licheknow.html
{% set patientLoggedIn = True %}
{% extends "base.html" %}

{% block head %}
    {{ super() }}
{% endblock head %}

{% block title %}LicheKnow{% endblock title %}


{% block nav_button_patient %}
    <div>
        <p class="nav-link link-dark">Welcome {{ patient_data['first_name']}}</p>
    </div>

    <div class="col-md-2 text-end position-relative">
        <a href="{{ url_for('patient_bp.logout') }}" class="btn text-light" id="log-in">Log-out</a>
    </div>
{% endblock nav_button_patient %}

{% block content %}

   <h1>LicheKnow</h1>

{% endblock content %}

GabayBuhay/templates/patient/lichencheck.html
{% set patientLoggedIn = True %}
{% extends "base.html" %}

{% block head %}
    {{ super() }}
{% endblock head %}

{% block title %}LichenCheck{% endblock title %}

{% block nav_button_patient %}
    <div>
        <p class="nav-link link-dark">Welcome {{ patient_data['first_name']}}</p>
    </div>

    <div class="col-md-2 text-end position-relative">
        <a href="{{ url_for('patient_bp.logout') }}" class="btn text-light" id="log-in">Log-out</a>
    </div>
{% endblock nav_button_patient %}

{% block content %}
    <h1>LichenCheck Page</h1>
{% endblock content %}

GabayBuhay/templates/patient/lichenhub.html
{% set patientLoggedIn = True %}
{% extends "base.html" %}

{% block head %}
    {{ super() }}
{% endblock head %}

{% block title %}LichenHub{% endblock title %}


{% block nav_button_patient %}
    <div>
        <p class="nav-link link-dark">Welcome {{ patient_data['first_name']}}</p>
    </div>

    <div class="col-md-2 text-end position-relative">
        <a href="{{ url_for('patient_bp.logout') }}" class="btn text-light" id="log-in">Log-out</a>
    </div>
{% endblock nav_button_patient %}

{% block content %}

   <h1>LichenHub</h1>

{% endblock content %}

GabayBuhay/templates/patient/patient.html
{% set patientLoggedIn = True %}
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/users/patient/patient_clinical_solutions.css') }}">
{% endblock head %}

{% block title %}Patient - Clinical Solutions{% endblock title %}


{% block nav_button_patient %}
    <div>
        <p class="nav-link link-dark">Welcome {{ patient_data['first_name']}}</p>
    </div>

    <div class="col-md-2 text-end position-relative">
        <a href="{{ url_for('home_bp.logout') }}" class="btn text-light" id="log-in">Log-out</a>
    </div>
{% endblock nav_button_patient %}

{% block content %}

    {# Section 1 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section1">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Enhance patient care and improvement outcomes with modern technology</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>GabayBuhay offers a modern healthcare tool for dermatology to provide decisions support for patients and dermatologists with improved healthcare services</b></p>
            </div>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button">Get to Know More!</a>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/Clinical_Solutions.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>
 
    {# Section 2 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section2">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Dermatology powered by Machine Learning</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>Machine Learning's trend is rising, and GabayBuhay saw this technology as the cornerstone in achieving improved healthcare quality outcomes. Have yourself a skin disease detector that can give an additional layer of screening.</b></p>
            </div>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button">Get Started</a>
        </div>
        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/LichenCheck.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>

    {# Section 3 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section3">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Streamlined and increase patient throughput</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>GabayBuhay offers a technology that provides a modern yet more efficient way of responsibly screening patients ahead of their appointment with a dermatologist. This saves time and improves patient throughput making it easy for the clinician to better recognize their patient.</b></p>
            </div>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button">Get Started</a>
        </div>
        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/DermAware.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>


    {# Section 4 #}
    <div class="container-fluid px-4 py-5 text-center">
      <div class="section section4">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">Learn Dermatology in just a few clicks</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>GabayBuhay extends its function as a Decision Support System by providing educational resources on multiple skin disorders ranging its rarity. This allows patients to make an informed decision about the skin condition diagnosis and learn dermatology with ease.</b></p>
            </div>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button">Get Started</a>
        </div>
        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/See_A_Doctor.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>
    

    {# Section 5 #}
    <div class="container-fluid px-4 py-5 my-5 text-center">
      <div class="section section5">
        <div class="lc-block mb-4">
            <div editable="rich">
                <h2 class="display-4 fw-bold">The Future of Healthcare has arrived!</h2>
            </div>
        </div>
        <div class="lc-block col-lg-8 mx-auto">
            <div editable="rich">
                <p class="lead"><b>Having an instant second opinion leads to better clinical outcomes thanks to the benefits of technology with GabayBuhay. The time has come and join the future of healthcare</b></p>
            </div>
        </div>

        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <a class="btn btn-primary btn-lg px-4 gap-3" href="#" role="button">Get Started</a>
        </div>
        <div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center">
            <img class="img-fluid custom-img-size" src="{{url_for('static', filename='imgs_&_svgs/the_future_image.svg')}}" width="" height="300" srcset="" sizes="" alt="">
        </div>
      </div>
    </div>
 

{% endblock content %}

GabayBuhay/templates/patient/patient_home.html
{% set patientLoggedIn = True %}
{% extends "base.html" %}

{% block head %}
    {{ super() }}
{% endblock head %}

{% block title %}Patient - Home{% endblock title %}


{% block nav_button_patient %}
    <div>
        <p class="nav-link link-dark">Welcome {{ patient_data['first_name']}}</p>
    </div>

    <div class="col-md-2 text-end position-relative">
        <a href="{{ url_for('guest_bp.logout') }}" class="btn text-light" id="log-in">Log-out</a>
    </div>
{% endblock nav_button_patient %}

{% block content %}

   <h1>Patient Home</h1>

{% endblock content %}