GabayBuhay/views/guest.py
import os
from flask import (Blueprint, current_app, render_template, request, redirect, url_for, session, jsonify, flash, make_response)
from werkzeug.utils import secure_filename
import db

guest_bp = Blueprint('guest_bp', __name__)

@guest_bp.route('/')
def index(): 
    return render_template('guest/index.html')


@guest_bp.route('/registration', methods=['POST'])
def registration():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']  # Retrieve the bcrypt instance from the app config
            user_data = request.form.to_dict(flat=False)  # Convert to a regular dictionary
            password = user_data['password'][0]  # Get the raw password from the form
            repeat_password = user_data['repeat_password'][0]
            
            # Hash the password using Flask-Bcrypt 
            hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
            hashed_repeat_password = bcrypt.generate_password_hash(repeat_password).decode('utf-8')
            # Replace the raw password with the hashed password in the user_data dictionary
            user_data['password'][0] = hashed_password
            user_data['repeat_password'][0] = hashed_repeat_password
            
            db.register_user(user_data)
            #Turn the user_data into a regular dictionary!! 
            user_data = {key: value[0] for key, value in user_data.items()}
            
            # Store user data in the session
            session['user_data'] = user_data
            
            #Redirects the user to his/her respective page based on their role (patient/clinician)
            return redirect(url_for('patient_bp.patient_home'))
            

@guest_bp.route('/log_in', methods=['POST'])
def log_in():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']
            email = request.form['email']
            password = request.form['password']

            user_data = db.fetch_user(email)

            if user_data is None:
                # Invalid credentials
                error_message = 'You have not yet created an account. Please try again.'
                return jsonify({'error': error_message})

            elif not bcrypt.check_password_hash(user_data['password'], password):
                # Invalid credentials
                error_message = 'Invalid credentials. Please try entering the password again.'
                return jsonify({'error': error_message})

            # Successful login
            session['user_data'] = user_data
            
            return jsonify({'success': 'Patient login successful', 'redirect_url': url_for('patient_bp.patient_home')})
      

@guest_bp.route('/about_us')
def about_us():
    return render_template('guest/about_us.html')

GabayBuhay/views/patient.py
from flask import (Blueprint, render_template, jsonify, request, redirect, session, make_response, url_for)

import db
patient_bp = Blueprint('patient_bp', __name__)

@patient_bp.route('/patient_home')
def patient_home():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/patient_home.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response


@patient_bp.route('/patient/lichencheck')
def lichencheck():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/lichencheck.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response


@patient_bp.route('/patient/lichenhub')
def lichenhub():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/lichenhub.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response


@patient_bp.route('/patient/licheknow')
def licheknow():
    # Your code to render the user's profile page
    user_data = session.get('user_data', None)
    if not user_data:
        return redirect(url_for('guest_bp.index'))  # Redirect to the index if not logged in
    
    # Create the response and set Cache-Control to prevent caching
    response = make_response(render_template('patient/licheknow.html', patient_data = user_data))
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    return response

@patient_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    # Remove session variables related to the user's login
    session.pop('user_data', None)  # Remove user ID or any other relevant session variables
    # Redirect the user to the login page or any other appropriate page
    return redirect(url_for('guest_bp.index')) 

GabayBuhay/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="UTF-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=0.5">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="shortcut icon" type="image/x-icon" href="{{url_for('static', filename='imgs_&_svgs/GaBu_logo1.png')}}" />
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
      *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
        .custom-navbar {
            background-color: #FFFFFF;
            position: sticky;
            top: 0;
            z-index: 3;
        }

        .nav-link{
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }
        .nav-link:hover {
            color: #5CC9CD;
        }
        #log-in {
            background-color: #5CC9CD;
            color:#FFFFFF;
            border: none;
            border-radius: 30px; /* Adjust the value to control button roundness */
            padding: 10px 20px;

        }
        body{
          min-height: 100%;
          display: flex;
          flex-direction: column;
        }

        #log-in:hover{
            background-color: #046a76;
        }

        footer {
          margin-top: auto;
          padding-left: 8%;
          padding-right: 8%;
          background-color: #5CC9CD;
        }

        footer .col-first{
          padding-top: 10px;
          
        }
        footer .col{
          text-align: center;
        }

        footer.nav-link {
          font-size: 18px;
        }
        footer .nav-link:hover{
            color:#FFFFFF;
        }


    </style>
  </head>
  {% endblock head %}

  <body>
    <!--NAVBAR (changes depending what the role of the user is.) -->
    {% block navbar %}

      {% if patientLoggedIn %}
        <header class="py-3 border-bottom custom-navbar">
            <div class="container">
                <div class="d-flex justify-content-between align-items-center">
                    <a href="{{url_for('patient_bp.patient_home')}}" class="d-flex align-items-center col-md-3 text-dark text-decoration-none" style="font-family: 'Questrial', sans-serif; font-size:larger;">
                    
                        <img src="{{url_for('static', filename='imgs_&_svgs/GaBu_logo1.png')}}" alt="GabayBuhay Icon" width="32px" height="32px" >
                        LichenCare                                                                                    
                    </a>
                    

                    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                        <li class="nav-item"><a href="{{url_for('patient_bp.lichencheck')}}" class="nav-link px-3 link-dark" id="lichenCheckBtn">LichenCheck</a></li>
                        <li class="nav-item"><a href="{{url_for('patient_bp.lichenhub')}}" class="nav-link px-3 link-dark" id="lichenHubBtn">LichenHub</a></li>
                        <li class="nav-item"><a href="{{url_for('patient_bp.licheknow')}}" class="nav-link px-3 link-dark" id="licheKnowBtn">LicheKnow</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link px-3 link-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="aboutUsBtn">
                                About Us
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Our Team</a>
                                <a class="dropdown-item" href="#">----------</a>
                                <a class="dropdown-item" href="#">Feedback</a>
                            </div>
                        </li>
                    </ul>

                      {% block nav_button_patient %}
                      
                      {% endblock nav_button_patient %}

                </div>
            </div>
        </header>
      {% elif guest %}
        <header class="py-3 border-bottom custom-navbar">
            <div class="container">
                <div class="d-flex justify-content-between align-items-center">
                    <a href="{{url_for('guest_bp.index')}}" class="d-flex align-items-center col-md-3 text-dark text-decoration-none" style="font-family: 'Questrial', sans-serif; font-size:larger;">
                    
                        <img src="{{url_for('static', filename='imgs_&_svgs/GaBu_logo1.png')}}" alt="GabayBuhay Icon" width="32px" height="32px" >
                        LichenCare                                               
                    </a>
                    
                    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                        <li class="nav-item"><a href="#" class="nav-link px-3 link-dark" id="lichenCheckBtn">LichenCheck</a></li>
                        <li class="nav-item"><a href="#" class="nav-link px-3 link-dark" id="lichenHubnBtn">LichenHub</a></li>
                        <li class="nav-item"><a href="#" class="nav-link px-3 link-dark" id="licheKnowBtn">LicheKnow</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link px-3 link-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="aboutUsBtn">
                                About Us
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{url_for('guest_bp.about_us')}}">Our Team</a> 
                                <a class="dropdown-item" href="#">--------</a>
                                <a class="dropdown-item" href="#">Feedback</a>
                            </div>
                        </li>
                    </ul>

                      <div class="col-md-3 mr-5 text-end position-relative">
                          <button id="log-in" type="button" class="btn text-light">Log-in</button>
                      </div>
                </div>
            </div>
        </header>
      {% endif %}

    {% endblock navbar %}

    <!--CONTENT BODY (replace with the specific contents for the corresponding page-->



    {% block content %}{% endblock %}



{% block footer %}

  {% if patientLoggedIn %}
    {# NEW FOOTER #}
    <footer class="border-top border-bottom pt-3 pb-3">
      <!-- First Row -->
      <div class="row row-cols-5">
        <div class="col-first">
          <a href="{{url_for('guest_bp.index')}}" class="link-dark">          
            <img src="{{url_for('static', filename='imgs_&_svgs/GaBu_logo2.png')}}" alt="GabayBuhay Icon" width="42px" height="42px" >                                                                          
          </a>
          <h6>LichenCare</h6>
          <h6 class="text-muted">Legazpi City, Albay</h6>
          <h6 class="text-muted">© 2023</h6>
        </div>

        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark">LichenCheck</a>
        </div>
        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark">LichenHub</a>
        </div>
        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark">LicheKnow</a>
        </div>
        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark">About Us</a>
          <ul class="nav flex-column">
            <li class="nav-item mb-2 px-3"><a href="#" class="nav-link p-0 text-muted">Our Team</a></li>
            <li class="nav-item mb-2 px-3"><a href="#" class="nav-link p-0 text-muted">-----------</a></li>
            <li class="nav-item mb-2 px-3"><a href="#" class="nav-link p-0 text-muted">Feedback</a></li>
          </ul>
        </div>
      </div>

      <!-- Separator Line -->
      <hr class="my-2">

      <!-- Second Row for Terms and Conditions -->
      <div class="row">
        <div class="col nav-link px-2 link-dark text-center">
          <h6><a href="#" class="nav-link px-3 link-dark">Terms and Conditions | Privacy Policy</a></h6>
        </div>
      </div>
    </footer>

  {% elif guest %}
    <footer class="border-top border-bottom pt-3 pb-3">
      <!-- First Row -->
      <div class="row row-cols-5">
        <div class="col-first">
          <a href="{{url_for('guest_bp.index')}}" class="link-dark">          
            <img src="{{url_for('static', filename='imgs_&_svgs/GaBu_logo2.png')}}" alt="GabayBuhay Icon" width="42px" height="42px" >                                                                          
          </a>
          <h6>LichenCare</h6>
          <h6 class="text-muted">Legazpi City, Albay</h6>
          <h6 class="text-muted">© 2023</h6>
        </div>

        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark" id="lichenCheckBtn">LichenCheck</a>
        </div>
        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark">LichenHub</a>
        </div>
        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark">LicheKnow</a>
        </div>
        <div class="col nav-link px-3 link-dark">
          <a href="#" class="nav-link px-3 link-dark">About Us</a>
          <ul class="nav flex-column">
            <li class="nav-item mb-2 px-3"><a href="{{url_for('guest_bp.about_us')}}" class="nav-link p-0 text-muted">Our Team</a></li>
            <li class="nav-item mb-2 px-3"><a href="#" class="nav-link p-0 text-muted">-----------</a></li>
            <li class="nav-item mb-2 px-3"><a href="#" class="nav-link p-0 text-muted">Feedback</a></li>
          </ul>
        </div>
      </div>

      <!-- Separator Line -->
      <hr class="my-2">

      <!-- Second Row for Terms and Conditions -->
      <div class="row">
        <div class="col nav-link px-2 link-dark text-center">
          <h6><a href="#" class="nav-link px-3 link-dark">Terms and Conditions | Privacy Policy</a></h6>
        </div>
      </div>
    </footer>
  {% endif %}

{% endblock footer %}
 
  
  {% block scripts %} 
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/guest/index_script.js') }}"></script>
  {% endblock scripts %}

  </body>
</html>