GabayBuhay/views/index.py
import os
from flask import (Blueprint, current_app, render_template, request, redirect, url_for, session, jsonify, flash, make_response)
from werkzeug.utils import secure_filename
import db

home_bp = Blueprint('home_bp', __name__)

@home_bp.route('/')
def index(): 
    roles = db.load_roles_from_db()
    return render_template('index/index.html', roles=roles)


@home_bp.route('/registration', methods=['POST'])
def registration():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']  # Retrieve the bcrypt instance from the app config
            user_data = request.form.to_dict(flat=False)  # Convert to a regular dictionary
            password = user_data['password'][0]  # Get the raw password from the form
            repeat_password = user_data['repeat_password'][0]
            
            # Hash the password using Flask-Bcrypt 
            hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
            hashed_repeat_password = bcrypt.generate_password_hash(repeat_password).decode('utf-8')
            # Replace the raw password with the hashed password in the user_data dictionary
            user_data['password'][0] = hashed_password
            user_data['repeat_password'][0] = hashed_repeat_password
            
            # Handle file upload
            if 'clinician_license' in request.files:
                file = request.files['clinician_license']
                if file.filename != '':
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
                    user_data['clinician_license'] = filename  # Save the filename to the database
                    
            db.register_user(user_data)
            #Turn the user_data into a regular dictionary!! 
            user_data = {key: value[0] for key, value in user_data.items()}
            
            # Store user data in the session
            session['user_data'] = user_data
            
            #Redirects the user to his/her respective page based on their role (patient/clinician)
            if user_data['account_type'] == '1':
                return redirect(url_for('patient_bp.patient_home'))
            elif user_data['account_type'] == '2':
                return redirect(url_for('clinician_bp.clinician_home'))
            

@home_bp.route('/log_in', methods=['POST'])
def log_in():
    if request.method == 'POST':
        with current_app.app_context():
            bcrypt = current_app.config['BCRYPT']
            email = request.form['email']
            password = request.form['password']

            user_data = db.fetch_user(email)

            if user_data is None:
                # Invalid credentials
                error_message = 'You have not yet created an account. Please try again.'
                return jsonify({'error': error_message})

            elif not bcrypt.check_password_hash(user_data['password'], password):
                # Invalid credentials
                error_message = 'Invalid credentials. Please try entering the password again.'
                return jsonify({'error': error_message})

            # Successful login
            session['user_data'] = user_data

            if user_data['role_id'] == 1:
                return jsonify({'success': 'Patient login successful', 'redirect_url': url_for('patient_bp.patient_home')})
            elif user_data['role_id'] == 2:
                return jsonify({'success': 'Clinician login successful', 'redirect_url': url_for('clinician_bp.clinician_home')})
      
      
@home_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    # Remove session variables related to the user's login
    session.pop('user_data', None)  # Remove user ID or any other relevant session variables
    # Redirect the user to the login page or any other appropriate page
    return redirect(url_for('home_bp.index')) 

GabayBuhay/templates/index/index.html
{% set nonUser = True %}
{% extends "base.html" %}

{% block head %}
    {# super() the index.html inherits the contents of basehtml head block #}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index_style/style.css') }}">

{% endblock head %}

{% block title %}GabayBuhay{% endblock title %}

{% block navbar %}
    {{ super() }}
{% endblock navbar %}

{% block content %}

<div class="row flex-lg-row-reverse align-items-center g-5 py-5 first">
        <div class="col-10 col-sm-8 col-lg-6">
            <img src="{{url_for('static', filename='imgs_&_svgs/derma.svg')}}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
        </div>

        <div class="col-lg-6 py-5 px-5">
            <h1 class="display-6 fw-bold lh-3 mb-3 text-wrap" style="font-family: 'Questrial', sans-serif;"> <b> Unlocking dermatological wisdom through information, guiding everyone with clinical decisions.</b></h1>

            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
            <button id="getStartedBtn" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Get Started</button>
            </div>
        </div>

        {# REGISTRATION FORM #}
        {# When user clicks get started, this will pop up#}
        {% include "index/registration-form.html" %}

        {# LOGIN FORM #}
        {# When user clicks get started, this will pop up#}
        {% include "index/login-form.html" %}
        <div id="overlay" class="overlay"></div>

</div>

<div class="row flex-lg align-items-center g-5 py-5 second">
        <div class="col-10 col-sm-8 col-lg-6">
            <img src="{{url_for('static', filename='imgs_&_svgs/derma2.svg')}}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700px" height="500px" loading="lazy">
        </div>

        <div class="col-lg-6 py-5 px-5">
            <h1 class="display-6 fw-bold lh-3 mb-3 text-wrap" style="font-family: 'Questrial', sans-serif;"> <b> Catalyzing Quality Clinical Outcomes Through Innovative Healthcare Technology.</b></h1>


            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
            <button id="knowMore" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Know More</button>
            </div>
        </div>        
</div>

{% endblock content%}

{% block script %}
    <script src="{{ url_for('static', filename='js/index/index_script.js') }}"></script>
{% endblock script %}

GabayBuhay/templates/index/login-form.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/index_style/login-form_style.css') }}">

<div id="loginFormPopup" class="login-form-popup">
    <div class="container main">
    
    <div id="error-message-container">
        <div id="error-message" class="error-message"  style="display: none;"></div>
    </div>

    <div id="success-message-container">
        <div id="success-message" class="success-message"  style="display: none;"></div>
    </div>


          <form action="{{ url_for('home_bp.log_in') }}" id="loginForm" method="POST" enctype="multipart/form-data">
              <div class="input-box">
                
                <div class="row header-row">
                    <div class="col-2 text-start">
                          
                    </div>
                    <div class="col-8 text-center">
                        <h2>Log-in</h2>
                    </div>
                    <div class="col-2 text-end">
                        
                    </div>
                </div>

                <div class="input-field">
                  <label for="email">Email</label>
                  <input type="email" class="input" name = "email" required/> 
                </div>

                <div class="input-field">
                  <label for="email">Password</label> 
                  <input type="password" class="input" name = "password" required/>
                </div>

                <div class="input-field" style="text-align: center;">
                  <input type="submit" class="submit" value="Login">
                </div>

                <!--Sign up here -->
                <div class="signin">
                  <span>Don't have an acount? <a id="redirect_to_register">Sign up here</a></span>
                </div>

              </div>  
        </form>        
    </div>
</div>


{% block script %}

{# JS FOR THE LOGIN-FORM ERROR HANDLING AND SUCCESSFUL LOG IN#}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const loginForm = document.getElementById("loginForm");
        const errorMessage = document.getElementById("error-message");
        const successMessage = document.getElementById("success-message");

        loginForm.addEventListener("submit", function (event) {
            event.preventDefault(); // Prevent the default form submission behavior

            const formData = new FormData(loginForm);

            fetch("{{ url_for('home_bp.log_in') }}", {
                method: "POST",
                body: formData,
            })
                .then(response => response.json())
                .then(data => {
                    if (data.error) {
                        errorMessage.textContent = data.error;
                        errorMessage.style.display = 'block'; // Show the error message
                    } else if (data.success) {
                        errorMessage.style.display = 'none';
                        successMessage.textContent = data.success; 
                        successMessage.style.display = 'block'; // Show the success message
                        setTimeout(function() {
                            window.location.href = data.redirect_url; // Redirect after a delay
                        }, 1000); // 1000 miliseconds (1s delay)
                    }
                })
                .catch(error => {
                    console.error("Error:", error);
                });
        });
    });
</script>

{% endblock script %}

GabayBuhay/templates/index/registration-form.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/index_style/registration-form_style.css') }}">

<!-- Registration form -->
<div id="registrationFormPopup" class="registration-form-popup">

    <!-- Your registration form HTML code goes here -->
    <div class="container main">
        <form action="{{ url_for('home_bp.registration') }}" method="POST" enctype="multipart/form-data">
            <div class="input-box">
                <div class="row header-row">
                    <div class="col-2 text-start">
                        
                    </div>
                    <div class="col-8 text-center">
                        <h2>Create an Account</h2>
                    </div>
                    <div class="col-2 text-end">
                        <button type="button" class="btn-close" aria-label="Close"></button>
                    </div>
                </div>
                
               <div class="row">
                    <label for="acc_type">Account Type</label>
                </div>

                <div class="row">
                <!-- Patient Radio Button -->
                    <div class="col-6 input-field">
                        <label class="modern-radio-label">
                            <input type="radio" name="account_type" value="{{ roles[0]['role_id'] }}" id="patientRadio"/>
                            <span>{{ roles[0]['role_name'] }}</span>
                        </label>
                    </div>
                    <!-- Clinician Radio Button -->
                    <div class="col-6 input-field">
                        <label class="modern-radio-label">
                            <input type="radio" name="account_type" value="{{ roles[1]['role_id'] }}" id="clinicianRadio"/>
                            <span>{{ roles[1]['role_name']}}</span>
                        </label>
                    </div>
                </div>

                <div class="row">
                    <!-- First Name -->
                    <div class="col-6 input-field">
                        <label for="email">First Name</label>
                        <input type="text" class="input" name="first_name" required/>
                    </div>

                    <!-- Last Name -->
                    <div class="col-6 input-field">
                        <label for="email">Last Name</label>
                        <input type="text" class="input" name="last_name" required/>
                    </div>
                </div>

                <!-- Username -->
                <div class="input-field">
                    <label for="email">Email</label>
                    <input type="email" class="input" id="email" name="email" required="" autocomplete="off">
                </div>

                <!-- Password -->
                <div class="input-field">
                    <label for="pass">Password</label>
                    <input type="password" class="input" id="pass" name="password" required/>
                </div>

                <!-- Confirm Password -->
                <div class="input-field">
                    <label for="pass">Confirm Password</label>
                    <input type="password" class="input" name="repeat_password" required/>
                </div>

                <!-- Upload License Div (Initially hidden, for CLINICIANS ONLY) -->
                <div class="input-field" id="licenseDiv">
                    <label for="license">Upload License</label>
                    <input type="file" name="clinician_license" placeholder="Upload License"/>
                </div>

            
                <div class="input-field terms">
                    <label>
                        <input type="checkbox" name="agree_to_terms" required>
                        I agree to the Terms of Service and Privacy Policy
                    </label>
                </div>

                <!-- Sign up button -->
                <div class="input-field" style="text-align: center;">
                    <input type="submit" class="submit" value="Sign Up" href="{{ url_for('home_bp.registration') }}">
                </div>

                <!-- Login here -->
                <div class="signin">
                    <span>Already have an account? <a id="redirect_to_login">Log in here</a></span>
                </div>
            </div>
        </form>
    </div>
</div>